# cost-analysis-workflow.yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: cost-analysis-pipeline
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
      - name: extract
        template: extract-task
      - name: transform
        dependencies: [extract]
        template: transform-task
      - name: load
        dependencies: [transform]
        template: load-task

  - name: extract-task
    script:
      image: python:3.9-slim
      command: [python]
      source: |
        from scripts.aws_cost_extractor import get_aws_cost_data
        get_aws_cost_data()

  - name: transform-task
    script:
      image: python:3.9-slim
      command: [python] 
      source: |
        from scripts.cost_transformer import normalize_cost_data
        normalize_cost_data(...)
