apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-query-scripts
data:
  query_metrics.py: |
    import requests

    def query_prometheus(query):
        url = "http://prometheus-server/api/v1/query"
        response = requests.get(url, params={"query": query})
        return response.json()

    if __name__ == "__main__":
        cpu_query = 'sum(rate(container_cpu_usage_seconds_total[5m]))'
        print(query_prometheus(cpu_query))
