apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    rule_files:
      - /etc/prometheus/rules.yml
    scrape_configs:
    - job_name: 'kube-cost-metrics'
      static_configs:
        - targets: ['kubecost-cost-analyzer:9090']
